language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
      env: CLIPPY=n
  include:
    - rust: nightly
      env: CLIPPY=y
    - rust: stable
      env: CHECK_README=y
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - CLIPPY: n
script: ./.travis.sh
