[package]
name = "diesel-derive-newtype"
version = "0.1.1"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
license = "Apache-2.0/MIT"
readme = "README.md"
categories = ["database", "rust-patterns"]
keywords = ["newtype", "derive"]
description = "Automatically connect newtypes to Diesel using their wrapped type"
repository = "https://github.com/quodlibetor/diesel-derive-newtype"

[badges]
travis-ci = { repository = "quodlibetor/diesel-derive-newtype", branch = "master" }

[dependencies]
syn = "0.11"
quote = "0.3.10"
diesel = "1"

[dev-dependencies]
diesel = { version = "1", features = ["sqlite"] }

[lib]
proc-macro = true
# required by cargo-readme until this is merged:
# https://github.com/livioribeiro/cargo-readme/pull/16
path = "src/lib.rs"
