[package]
name = "diesel-newtype"
version = "0.1.0"
authors = ["Brandon W Maister <bwm@knewton.com>"]

[dependencies]
diesel = "0.14.0"
syn = { version = "0.11", features = ["parsing", "printing"] }
quote = "0.3.10"

[dev-dependencies]
dotenv = "*"
diesel = { version = "0.14.0", features = ["sqlite"] }
diesel_codegen = { version = "0.14.0", features = ["sqlite"] }

[lib]
proc-macro = true
