[package]
name = "diesel-derive-newtype"
version = "0.1.0"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
license = "Apache-2.0/MIT"
readme = "README.md"
categories = []

[dependencies]
syn = "0.11"
quote = "0.3.10"
# Assuming 0.99 follows the contract it claims this should work with 1.0, too
diesel = ">=0.16,<1.0"

[dev-dependencies]
diesel = { version = ">=0.16.0,<1.0", features = ["sqlite"] }
diesel_codegen = { version = ">=0.16.0,<1.0", features = ["sqlite", "postgres"] }

[lib]
proc-macro = true
# required by cargo-readme until this is merged:
# https://github.com/livioribeiro/cargo-readme/pull/16
path = "src/lib.rs"
