[package]
name = "diesel-derive-newtype"
version = "0.1.0"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]

[dependencies]
syn = "0.11"
quote = "0.3.10"
diesel = "<0.17,>=0.15.0"

[dev-dependencies]
diesel = { version = "<0.17,>=0.15.0", features = ["sqlite"] }
diesel_codegen = { version = "<0.17,>=0.15.0", features = ["sqlite", "postgres"] }

[lib]
proc-macro = true
