[package]
name = "diesel-derive-newtype"
version = "0.1.0"
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
license = "Apache-2.0/MIT"
readme = "README.md"
categories = []

[dependencies]
syn = "0.11"
quote = "0.3.10"
diesel = ">=0.16,<2.0"

[dev-dependencies]
diesel = { version = ">=0.16.0,<2.0", features = ["sqlite"] }

[lib]
proc-macro = true
# required by cargo-readme until this is merged:
# https://github.com/livioribeiro/cargo-readme/pull/16
path = "src/lib.rs"
